### ISSUE TITLE
Scoring implementation

### ISSUE THREAD

**Issue by Kiritsu** [Kiritsu/PakMan#4]
We need to implement scoring. I think we can easily do it with the TP3 of simbad in our uni eureka.

(https://eureka-old.univ-lehavre.fr/mod/resource/view.php?id=48608 at "Cherry Agent" part)

- [x] Add CherryAgent Object
- [x] Parse Point from text file
- [x] Detect when Pak goes over a Point (CherryAgent Object) and give it points
- [x] Add a panel with the score

**Comment by Shinzoo** [comment]
https://github.com/Kiritsu/PakMan/commit/f80c2118df8320aab1639427b25d9c7d0dd773b5 : 

Added "Point" to PakEnvironmentParser.
Added a Point to the map file.

**Comment by Kiritsu** [comment]
Done.
